Repository golagola2020/hango-server, pull requests merged in 2020-10, with the labels that each got.

#116 [admin/editDesign] 관리자 시스템 UI 수정
  server/client/views/admin/vending/detail.ejs
  server/client/views/admin/vending/main.ejs
  server/public/css/admin/login.css
  server/public/css/admin/vending/create.css
  server/public/css/admin/vending/main.css
  server/public/css/reset.css
Labels: 관리자 웹, 디자인

#118 [admin/user] 사용자 관리 화면 구현
  server/client/views/admin/user/detail.ejs
  server/client/views/admin/user/main.ejs
  server/client/views/admin/user/update.ejs
  server/public/css/admin/user/detail.css
  server/public/css/admin/user/main.css
  server/public/css/admin/user/update.css
  server/public/js/admin/home.js
  server/public/js/admin/user/detail.js
  server/public/js/admin/user/main.js
  server/public/js/admin/user/update.js
  server/routes/admin/user/main.js
  server/server.js
Labels: DB, 관리자 웹, 기능 추가, 서버

#121 [template] hango-server 템플릿 수정
  .github/ISSUE_TEMPLATE/default.md
Labels: 기능 개선

#122 [admin/search] 관리자 시스템에 검색 기능 추가
  server/client/views/admin/user/main.ejs
  server/client/views/admin/vending/main.ejs
  server/public/css/admin/user/main.css
  server/public/css/admin/vending/main.css
  server/public/css/reset.css
  server/public/js/admin/user/main.js
  server/public/js/admin/vending/main.js
  server/routes/admin/user/main.js
  server/routes/admin/vending/main.js
Labels: DB, 관리자 웹, 기능 추가, 서버

#123 [v1.1.0] 서버 v1.1.0 개발 완료
  .gitignore
  server/client/views/admin/home.ejs
  server/client/views/admin/login.ejs
  server/client/views/admin/user/detail.ejs
  server/client/views/admin/user/main.ejs
  server/client/views/admin/user/update.ejs
  server/client/views/admin/vending/create.ejs
  server/client/views/admin/vending/detail.ejs
  server/client/views/admin/vending/main.ejs
  server/client/views/admin/vending/update.ejs
  server/package-lock.json
  server/package.json
  server/public/css/admin/home.css
  server/public/css/admin/login.css
  server/public/css/admin/user/detail.css
  server/public/css/admin/user/main.css
  server/public/css/admin/user/update.css
  server/public/css/admin/vending/create.css
  server/public/css/admin/vending/detail.css
  server/public/css/admin/vending/main.css
  server/public/css/admin/vending/update.css
  server/public/css/reset.css
  server/public/images/favicon.ico
  server/public/js/admin/home.js
  server/public/js/admin/login.js
  server/public/js/admin/user/detail.js
  server/public/js/admin/user/main.js
  server/public/js/admin/user/update.js
  server/public/js/admin/vending/create.js
  server/public/js/admin/vending/detail.js
  server/public/js/admin/vending/main.js
  server/public/js/admin/vending/update.js
  server/routes/admin/home.js
  server/routes/admin/login.js
  server/routes/admin/user/main.js
  server/routes/admin/vending/main.js
  server/routes/mobile/mobile.js
  server/routes/mobile/vending.js
  server/routes/rasp.js
  server/server.js
Labels: DB, 관리자 웹, 기능 추가, 서버

#126 [mobile/stats] 가공된 매출 데이터를 응답하도록 수정
  .github/ISSUE_TEMPLATE/default.md
  server/routes/mobile/mobile.js
Labels: DB, 기능 개선, 서버

#127 [mobile/stats] 유저, 자판기, 음료수별 판매 데이터 제공 API 분리
  server/routes/mobile/mobile.js
  server/routes/mobile/stats.js
  server/server.js
Labels: 기능 개선, 서버

#128 [hash] 모바일 로그인, 회원가입시 해쉬함수 적용
  server/package-lock.json
  server/package.json
  server/routes/mobile/mobile.js
Labels: DB, 기능 개선, 서버

#133 [docs] Node 템플릿 적용
  .gitignore
Labels: 문서화, 비개발

#136 [docs] Hango 기여 지침서 초안 발행
  CONTRIBUTING.md
Labels: 문서화, 비개발

#140 [mobile/user/update] 모바일 회원 update API 수정 및 암호 해시화
  server/src/routes/mobile/mobile.js
Labels: 기능 개선, 서버

#141 [mobile/notification] 알림 API 설계 및 구현 #138
  server/src/routes/mobile/mobile.js
Labels: DB, 기능 추가, 서버

#143 [admin] 회원가입 및 로그인시 Hango에게 승인된 유저만 로그인 되도록 변경
  server/package-lock.json
  server/package.json
  server/src/client/views/admin/signup.ejs
  server/src/public/js/admin/signup.js
  server/src/routes/admin/login.js
Labels: DB, 관리자 웹, 기능 추가, 서버

#149 [DB] MySQL 일정시간동안 접속이 없으면 종료되는 오류 해결 #146
  .dockerignore
  Dockerfile
  server/src/database/db.js
Labels: DB, 기능 개선, 버그, 서버

#150 [mobile/hotfix] 로그인한 유저가 등록된 자판기가 없을 경우 발생하는 오류 해결
  server/src/routes/mobile/vending.js
Labels: 버그, 서버

#151 [admin/passport] 관리자시스템에 세션 저장 기능 추가
  server/package-lock.json
  server/package.json
  server/server.js
  server/src/public/js/admin/login.js
  server/src/routes/admin/home.js
  server/src/routes/admin/login.js
  server/src/routes/admin/user/main.js
  server/src/routes/admin/vending/main.js
Labels: DB, 관리자 웹, 기능 추가, 서버

#157 [docs] v1.3.1 리드미 발행
  README.md
Labels: 문서화, 비개발, 서버

#158 [docs] Apache License 2.0 등록
  LICENSE
Labels: 문서화, 비개발, 서버

#159 [docs] v1.3.1 리드미 발행
  README.md
Labels: 문서화, 비개발, 서버

#162 [v.1.3.1] 개발 완료
  LICENSE
  README.md
  compose/hango/Dockerfile-dev
  compose/hango/start-dev.sh
  db/init.sql
  docker-compose.yml
  server/package.json
  server/src/client/views/admin/home.ejs
  server/src/client/views/admin/user/detail.ejs
  server/src/client/views/admin/user/main.ejs
  server/src/client/views/admin/user/update.ejs
  server/src/client/views/admin/vending/create.ejs
  server/src/client/views/admin/vending/main.ejs
  server/src/database/db.js
Labels: 배포, 서버

#165 [v1.4.0] 404 에러페이지 추가
  server/package.json
  server/server.js
  server/src/client/views/404.ejs
  server/src/public/css/404.css
Labels: 관리자 웹, 기능 추가, 서버

#166 [V1.4.0/docker compose] 도커 MySQL 초기 데이터셋 한글로 저장되도록 수정
  .dockerignore
  db/config/utf-8.cnf
  db/sql/init.sql
  docker-compose.yml
  server/src/public/js/admin/signup.js
  server/src/routes/admin/login.js
Labels: DB, 기능 개선, 서버

#167 [docs] v1.4.0 리드미 발행
  README.md
Labels: 문서화, 비개발, 서버

#168 [v1.4.0] Hango Server v1.4.0 배포
  .dockerignore
  README.md
  db/config/utf-8.cnf
  db/sql/init.sql
  docker-compose.yml
  server/package.json
  server/server.js
  server/src/client/views/404.ejs
  server/src/public/css/404.css
  server/src/public/js/admin/signup.js
  server/src/routes/admin/login.js
Labels: 배포, 서버

#169 [v1.4.1] Hango Server v1.4.1 배포
  server/src/routes/admin/login.js
Labels: 관리자 웹, 배포, 서버
